-- ============================================================
-- SPMB SDN 02 CIBADAK — DATABASE SCHEMA (ARSIP LENGKAP)
-- Supabase / PostgreSQL
-- Dibuat: 12 Mei 2026
-- ============================================================

-- ============================================================
-- 1. TABEL: pengaturan
-- Menyimpan konfigurasi portal SPMB
-- ============================================================
CREATE TABLE IF NOT EXISTS pengaturan (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_setting TEXT NOT NULL UNIQUE,
    status      TEXT,
    created_at  TIMESTAMPTZ DEFAULT now(),
    updated_at  TIMESTAMPTZ DEFAULT now()
);

-- Seed data pengaturan
INSERT INTO pengaturan (nama_setting, status) VALUES
    ('jadwal_buka',         '2026-05-10T08:00:00+07:00'),
    ('jadwal_tutup',        '2026-05-20T23:59:59+07:00'),
    ('maintenance',         'OFF'),
    ('edit_data_mandiri',   'OFF'),
    ('kepala_sekolah',      'NAMA KEPALA SEKOLAH'),
    ('nip_kepsek',          '000000000000000000'),
    ('password_admin_spmb', 'admin123')
ON CONFLICT (nama_setting) DO NOTHING;

-- ============================================================
-- 2. TABEL: pendaftar_dapodik
-- Data utama pendaftaran peserta didik baru
-- ============================================================
CREATE TABLE IF NOT EXISTS pendaftar_dapodik (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- A. IDENTITAS PESERTA DIDIK
    nama                TEXT,
    jk                  TEXT,           -- L / P
    agama               TEXT,
    nik                 TEXT,           -- 16 digit NIK anak
    nisn                TEXT,           -- 10 digit (opsional)
    tempat_lahir        TEXT,
    tanggal_lahir       DATE,
    nipd                TEXT,           -- Nomor Induk Peserta Didik (opsional)
    anak_ke             INTEGER,
    kebutuhan_khusus    TEXT,

    -- B. ALAMAT DOMISILI
    alamat              TEXT,
    rt                  TEXT,
    rw                  TEXT,
    dusun               TEXT,
    kecamatan           TEXT,
    kelurahan           TEXT,
    kode_pos            TEXT,
    jenis_tinggal       TEXT,
    alat_transportasi   TEXT,
    jarak_sekolah       INTEGER,        -- dalam Km

    -- C. KONTAK & DATA FISIK
    hp                  TEXT,           -- No. HP / WhatsApp (wajib)
    telepon             TEXT,           -- No. Telepon (opsional)
    email               TEXT,
    tinggi_badan        INTEGER,        -- cm
    berat_badan         INTEGER,        -- kg
    lingkar_kepala      INTEGER,        -- cm
    jml_saudara         INTEGER,

    -- D. DOKUMEN & KESEJAHTERAAN
    no_kk               TEXT,           -- 16 digit No. KK
    no_akta             TEXT,           -- No. Registrasi Akta Lahir
    penerima_kps        TEXT,           -- Ya / Tidak
    no_kps              TEXT,
    penerima_kip        TEXT,           -- Ya / Tidak
    no_kip              TEXT,
    nama_kip            TEXT,
    no_kks              TEXT,           -- No. Kartu Keluarga Sejahtera
    layak_pip           TEXT,           -- Ya / Tidak
    alasan_pip          TEXT,
    bank                TEXT,
    no_rekening         TEXT,
    atas_nama_rekening  TEXT,

    -- E. DATA AYAH KANDUNG
    nama_ayah           TEXT,
    nik_ayah            TEXT,           -- 16 digit
    tahun_lahir_ayah    TEXT,
    pendidikan_ayah     TEXT,
    pekerjaan_ayah      TEXT,
    penghasilan_ayah    TEXT,

    -- F. DATA IBU KANDUNG
    nama_ibu            TEXT,
    nik_ibu             TEXT,           -- 16 digit
    tahun_lahir_ibu     TEXT,
    pendidikan_ibu      TEXT,
    pekerjaan_ibu       TEXT,
    penghasilan_ibu     TEXT,

    -- G. DATA WALI (semua opsional)
    nama_wali           TEXT,
    nik_wali            TEXT,           -- 16 digit
    tahun_lahir_wali    TEXT,
    pendidikan_wali     TEXT,
    pekerjaan_wali      TEXT,
    penghasilan_wali    TEXT,

    -- H. AKADEMIK & LAINNYA
    sekolah_asal        TEXT,

    -- METADATA
    status_pendaftaran  TEXT DEFAULT 'Tahap 1',  -- Tahap 1 / Diterima / Ditolak
    created_at          TIMESTAMPTZ DEFAULT now(),
    updated_at          TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- 3. INDEXES
-- Optimasi query untuk pencarian NIK dan HP
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_pendaftar_nik ON pendaftar_dapodik (nik);
CREATE INDEX IF NOT EXISTS idx_pendaftar_hp ON pendaftar_dapodik (hp);
CREATE INDEX IF NOT EXISTS idx_pendaftar_nama ON pendaftar_dapodik USING gin (nama gin_trgm_ops);
-- ^ Jika gin_trgm_ops error, jalankan dulu: CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE INDEX IF NOT EXISTS idx_pengaturan_nama ON pengaturan (nama_setting);

-- ============================================================
-- 4. AUTO-UPDATE updated_at (TRIGGER)
-- ============================================================
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger untuk pendaftar_dapodik
DROP TRIGGER IF EXISTS set_updated_at_pendaftar ON pendaftar_dapodik;
CREATE TRIGGER set_updated_at_pendaftar
    BEFORE UPDATE ON pendaftar_dapodik
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();

-- Trigger untuk pengaturan
DROP TRIGGER IF EXISTS set_updated_at_pengaturan ON pengaturan;
CREATE TRIGGER set_updated_at_pengaturan
    BEFORE UPDATE ON pengaturan
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();

-- ============================================================
-- 5. ROW LEVEL SECURITY (RLS)
-- Disesuaikan untuk akses publik portal SPMB
-- ============================================================

-- pendaftar_dapodik: izinkan semua operasi (public portal)
ALTER TABLE pendaftar_dapodik ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert" ON pendaftar_dapodik
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public select" ON pendaftar_dapodik
    FOR SELECT USING (true);

CREATE POLICY "Allow public update" ON pendaftar_dapodik
    FOR UPDATE USING (true) WITH CHECK (true);

-- pengaturan: izinkan baca publik, update via admin (anon key)
ALTER TABLE pengaturan ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public select pengaturan" ON pengaturan
    FOR SELECT USING (true);

CREATE POLICY "Allow public update pengaturan" ON pengaturan
    FOR UPDATE USING (true) WITH CHECK (true);

-- ============================================================
-- 6. REALTIME
-- Aktifkan Supabase Realtime untuk monitoring live
-- ============================================================
ALTER PUBLICATION supabase_realtime ADD TABLE pendaftar_dapodik;
ALTER PUBLICATION supabase_realtime ADD TABLE pengaturan;

-- ============================================================
-- 7. QUERY TAMBAHAN: Hanya edit_data_mandiri (jika sudah ada tabel)
-- Jalankan ini jika tabel pengaturan sudah ada dan hanya
-- perlu menambahkan setting baru.
-- ============================================================
-- INSERT INTO pengaturan (nama_setting, status)
-- VALUES ('edit_data_mandiri', 'OFF')
-- ON CONFLICT (nama_setting) DO NOTHING;

-- ============================================================
-- CATATAN:
-- - Kapasitas kuota (72 pendaftar) dikelola di kode frontend
--   via useRealtimeStats hook (COUNT dari pendaftar_dapodik).
-- - Password admin SPMB disimpan di tabel pengaturan dengan
--   nama_setting = 'password_admin_spmb'.
-- - Semua kolom NIK disimpan sebagai TEXT (tanpa spasi/strip),
--   pembersihan dilakukan di frontend sebelum INSERT/UPDATE.
-- ============================================================
